// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.2
// source: order/house.order

package house

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           string                 `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Sd            string                 `protobuf:"bytes,2,opt,name=sd,proto3" json:"sd,omitempty"`
	Ed            string                 `protobuf:"bytes,3,opt,name=ed,proto3" json:"ed,omitempty"`
	Sk            string                 `protobuf:"bytes,4,opt,name=sk,proto3" json:"sk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_proto_house_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{0}
}

func (x *SearchReq) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *SearchReq) GetSd() string {
	if x != nil {
		return x.Sd
	}
	return ""
}

func (x *SearchReq) GetEd() string {
	if x != nil {
		return x.Ed
	}
	return ""
}

func (x *SearchReq) GetSk() string {
	if x != nil {
		return x.Sk
	}
	return ""
}

type IndexReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexReq) Reset() {
	*x = IndexReq{}
	mi := &file_proto_house_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexReq) ProtoMessage() {}

func (x *IndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexReq.ProtoReflect.Descriptor instead.
func (*IndexReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{1}
}

type DetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseId       string                 `protobuf:"bytes,1,opt,name=houseId,proto3" json:"houseId,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailReq) Reset() {
	*x = DetailReq{}
	mi := &file_proto_house_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailReq) ProtoMessage() {}

func (x *DetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailReq.ProtoReflect.Descriptor instead.
func (*DetailReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{2}
}

func (x *DetailReq) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

func (x *DetailReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type DetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         string                 `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data          *DetailData            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResp) Reset() {
	*x = DetailResp{}
	mi := &file_proto_house_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResp) ProtoMessage() {}

func (x *DetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResp.ProtoReflect.Descriptor instead.
func (*DetailResp) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{3}
}

func (x *DetailResp) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *DetailResp) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *DetailResp) GetData() *DetailData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DetailData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	House         *HouseDetail           `protobuf:"bytes,1,opt,name=house,proto3" json:"house,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailData) Reset() {
	*x = DetailData{}
	mi := &file_proto_house_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailData) ProtoMessage() {}

func (x *DetailData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailData.ProtoReflect.Descriptor instead.
func (*DetailData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{4}
}

func (x *DetailData) GetHouse() *HouseDetail {
	if x != nil {
		return x.House
	}
	return nil
}

func (x *DetailData) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type HouseDetail struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Acreage  int32                  `protobuf:"varint,1,opt,name=acreage,proto3" json:"acreage,omitempty"`
	Address  string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Beds     string                 `protobuf:"bytes,3,opt,name=beds,proto3" json:"beds,omitempty"`
	Capacity int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// comment
	Comments []*CommentData `protobuf:"bytes,5,rep,name=comments,proto3" json:"comments,omitempty"`
	Deposit  int32          `protobuf:"varint,6,opt,name=deposit,proto3" json:"deposit,omitempty"`
	// 展示所有的图片 主图片和副图片
	Facilities    []int32  `protobuf:"varint,7,rep,packed,name=facilities,proto3" json:"facilities,omitempty"` //家具id切片
	Hid           int32    `protobuf:"varint,8,opt,name=hid,proto3" json:"hid,omitempty"`
	ImgUrls       []string `protobuf:"bytes,9,rep,name=img_urls,json=imgUrls,proto3" json:"img_urls,omitempty"`
	MaxDays       int32    `protobuf:"varint,10,opt,name=max_days,json=maxDays,proto3" json:"max_days,omitempty"`
	MinDays       int32    `protobuf:"varint,11,opt,name=min_days,json=minDays,proto3" json:"min_days,omitempty"`
	Price         int32    `protobuf:"varint,12,opt,name=price,proto3" json:"price,omitempty"`
	RoomCount     int32    `protobuf:"varint,13,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	Title         string   `protobuf:"bytes,14,opt,name=title,proto3" json:"title,omitempty"`
	Unit          string   `protobuf:"bytes,15,opt,name=unit,proto3" json:"unit,omitempty"`
	UserAvatar    string   `protobuf:"bytes,16,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	UserId        int32    `protobuf:"varint,17,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string   `protobuf:"bytes,18,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseDetail) Reset() {
	*x = HouseDetail{}
	mi := &file_proto_house_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseDetail) ProtoMessage() {}

func (x *HouseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseDetail.ProtoReflect.Descriptor instead.
func (*HouseDetail) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{5}
}

func (x *HouseDetail) GetAcreage() int32 {
	if x != nil {
		return x.Acreage
	}
	return 0
}

func (x *HouseDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HouseDetail) GetBeds() string {
	if x != nil {
		return x.Beds
	}
	return ""
}

func (x *HouseDetail) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HouseDetail) GetComments() []*CommentData {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *HouseDetail) GetDeposit() int32 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *HouseDetail) GetFacilities() []int32 {
	if x != nil {
		return x.Facilities
	}
	return nil
}

func (x *HouseDetail) GetHid() int32 {
	if x != nil {
		return x.Hid
	}
	return 0
}

func (x *HouseDetail) GetImgUrls() []string {
	if x != nil {
		return x.ImgUrls
	}
	return nil
}

func (x *HouseDetail) GetMaxDays() int32 {
	if x != nil {
		return x.MaxDays
	}
	return 0
}

func (x *HouseDetail) GetMinDays() int32 {
	if x != nil {
		return x.MinDays
	}
	return 0
}

func (x *HouseDetail) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *HouseDetail) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

func (x *HouseDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HouseDetail) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *HouseDetail) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *HouseDetail) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HouseDetail) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type CommentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       string                 `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime         string                 `protobuf:"bytes,2,opt,name=ctime,proto3" json:"ctime,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentData) Reset() {
	*x = CommentData{}
	mi := &file_proto_house_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentData) ProtoMessage() {}

func (x *CommentData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentData.ProtoReflect.Descriptor instead.
func (*CommentData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{6}
}

func (x *CommentData) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CommentData) GetCtime() string {
	if x != nil {
		return x.Ctime
	}
	return ""
}

func (x *CommentData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_proto_house_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{7}
}

func (x *GetReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         string                 `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data          *GetData               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_proto_house_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{8}
}

func (x *GetResp) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *GetResp) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *GetResp) GetData() *GetData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Houses        []*Houses              `protobuf:"bytes,1,rep,name=houses,proto3" json:"houses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetData) Reset() {
	*x = GetData{}
	mi := &file_proto_house_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetData) ProtoMessage() {}

func (x *GetData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetData.ProtoReflect.Descriptor instead.
func (*GetData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{9}
}

func (x *GetData) GetHouses() []*Houses {
	if x != nil {
		return x.Houses
	}
	return nil
}

type Houses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AreaName      string                 `protobuf:"bytes,2,opt,name=area_name,json=areaName,proto3" json:"area_name,omitempty"`
	Ctime         string                 `protobuf:"bytes,3,opt,name=ctime,proto3" json:"ctime,omitempty"`
	HouseId       int32                  `protobuf:"varint,4,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,5,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	OrderCount    int32                  `protobuf:"varint,6,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Price         int32                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	RoomCount     int32                  `protobuf:"varint,8,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	Title         string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	UserAvatar    string                 `protobuf:"bytes,10,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Houses) Reset() {
	*x = Houses{}
	mi := &file_proto_house_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Houses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Houses) ProtoMessage() {}

func (x *Houses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Houses.ProtoReflect.Descriptor instead.
func (*Houses) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{10}
}

func (x *Houses) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Houses) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *Houses) GetCtime() string {
	if x != nil {
		return x.Ctime
	}
	return ""
}

func (x *Houses) GetHouseId() int32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *Houses) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *Houses) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *Houses) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Houses) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

func (x *Houses) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Houses) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

type ImgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseId       string                 `protobuf:"bytes,1,opt,name=houseId,proto3" json:"houseId,omitempty"`
	ImgData       []byte                 `protobuf:"bytes,2,opt,name=imgData,proto3" json:"imgData,omitempty"`
	FileExt       string                 `protobuf:"bytes,3,opt,name=fileExt,proto3" json:"fileExt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImgReq) Reset() {
	*x = ImgReq{}
	mi := &file_proto_house_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgReq) ProtoMessage() {}

func (x *ImgReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgReq.ProtoReflect.Descriptor instead.
func (*ImgReq) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{11}
}

func (x *ImgReq) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

func (x *ImgReq) GetImgData() []byte {
	if x != nil {
		return x.ImgData
	}
	return nil
}

func (x *ImgReq) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

type ImgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         string                 `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data          *ImgData               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImgResp) Reset() {
	*x = ImgResp{}
	mi := &file_proto_house_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgResp) ProtoMessage() {}

func (x *ImgResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgResp.ProtoReflect.Descriptor instead.
func (*ImgResp) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{12}
}

func (x *ImgResp) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *ImgResp) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *ImgResp) GetData() *ImgData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImgData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImgData) Reset() {
	*x = ImgData{}
	mi := &file_proto_house_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgData) ProtoMessage() {}

func (x *ImgData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgData.ProtoReflect.Descriptor instead.
func (*ImgData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{13}
}

func (x *ImgData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acreage       string                 `protobuf:"bytes,1,opt,name=acreage,proto3" json:"acreage,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AreaId        string                 `protobuf:"bytes,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Beds          string                 `protobuf:"bytes,4,opt,name=beds,proto3" json:"beds,omitempty"`
	Capacity      string                 `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Deposit       string                 `protobuf:"bytes,6,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Facility      []string               `protobuf:"bytes,7,rep,name=facility,proto3" json:"facility,omitempty"`
	MaxDays       string                 `protobuf:"bytes,8,opt,name=max_days,json=maxDays,proto3" json:"max_days,omitempty"`
	MinDays       string                 `protobuf:"bytes,9,opt,name=min_days,json=minDays,proto3" json:"min_days,omitempty"`
	Price         string                 `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	RoomCount     string                 `protobuf:"bytes,11,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	Title         string                 `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	Unit          string                 `protobuf:"bytes,13,opt,name=unit,proto3" json:"unit,omitempty"`
	UserName      string                 `protobuf:"bytes,14,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_house_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{14}
}

func (x *Request) GetAcreage() string {
	if x != nil {
		return x.Acreage
	}
	return ""
}

func (x *Request) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Request) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *Request) GetBeds() string {
	if x != nil {
		return x.Beds
	}
	return ""
}

func (x *Request) GetCapacity() string {
	if x != nil {
		return x.Capacity
	}
	return ""
}

func (x *Request) GetDeposit() string {
	if x != nil {
		return x.Deposit
	}
	return ""
}

func (x *Request) GetFacility() []string {
	if x != nil {
		return x.Facility
	}
	return nil
}

func (x *Request) GetMaxDays() string {
	if x != nil {
		return x.MaxDays
	}
	return ""
}

func (x *Request) GetMinDays() string {
	if x != nil {
		return x.MinDays
	}
	return ""
}

func (x *Request) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Request) GetRoomCount() string {
	if x != nil {
		return x.RoomCount
	}
	return ""
}

func (x *Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Request) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Request) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         string                 `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data          *HouseData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_house_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{15}
}

func (x *Response) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *Response) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *Response) GetData() *HouseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type HouseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseId       string                 `protobuf:"bytes,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseData) Reset() {
	*x = HouseData{}
	mi := &file_proto_house_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseData) ProtoMessage() {}

func (x *HouseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseData.ProtoReflect.Descriptor instead.
func (*HouseData) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{16}
}

func (x *HouseData) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

var File_proto_house_proto protoreflect.FileDescriptor

const file_proto_house_proto_rawDesc = "" +
	"\n" +
	"\x11proto/house.order\x12\x05house\"M\n" +
	"\tSearchReq\x12\x10\n" +
	"\x03aid\x18\x01 \x01(\tR\x03aid\x12\x0e\n" +
	"\x02sd\x18\x02 \x01(\tR\x02sd\x12\x0e\n" +
	"\x02ed\x18\x03 \x01(\tR\x02ed\x12\x0e\n" +
	"\x02sk\x18\x04 \x01(\tR\x02sk\"\n" +
	"\n" +
	"\bIndexReq\"A\n" +
	"\tDetailReq\x12\x18\n" +
	"\ahouseId\x18\x01 \x01(\tR\ahouseId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\"a\n" +
	"\n" +
	"DetailResp\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\tR\x05errno\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg\x12%\n" +
	"\x04data\x18\x03 \x01(\v2\x11.house.DetailDataR\x04data\"O\n" +
	"\n" +
	"DetailData\x12(\n" +
	"\x05house\x18\x01 \x01(\v2\x12.house.HouseDetailR\x05house\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"\xf4\x03\n" +
	"\vHouseDetail\x12\x18\n" +
	"\aacreage\x18\x01 \x01(\x05R\aacreage\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04beds\x18\x03 \x01(\tR\x04beds\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12.\n" +
	"\bcomments\x18\x05 \x03(\v2\x12.house.CommentDataR\bcomments\x12\x18\n" +
	"\adeposit\x18\x06 \x01(\x05R\adeposit\x12\x1e\n" +
	"\n" +
	"facilities\x18\a \x03(\x05R\n" +
	"facilities\x12\x10\n" +
	"\x03hid\x18\b \x01(\x05R\x03hid\x12\x19\n" +
	"\bimg_urls\x18\t \x03(\tR\aimgUrls\x12\x19\n" +
	"\bmax_days\x18\n" +
	" \x01(\x05R\amaxDays\x12\x19\n" +
	"\bmin_days\x18\v \x01(\x05R\aminDays\x12\x14\n" +
	"\x05price\x18\f \x01(\x05R\x05price\x12\x1d\n" +
	"\n" +
	"room_count\x18\r \x01(\x05R\troomCount\x12\x14\n" +
	"\x05title\x18\x0e \x01(\tR\x05title\x12\x12\n" +
	"\x04unit\x18\x0f \x01(\tR\x04unit\x12\x1f\n" +
	"\vuser_avatar\x18\x10 \x01(\tR\n" +
	"userAvatar\x12\x17\n" +
	"\auser_id\x18\x11 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x12 \x01(\tR\buserName\"Z\n" +
	"\vCommentData\x12\x18\n" +
	"\acomment\x18\x01 \x01(\tR\acomment\x12\x14\n" +
	"\x05ctime\x18\x02 \x01(\tR\x05ctime\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\"$\n" +
	"\x06GetReq\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\"[\n" +
	"\aGetResp\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\tR\x05errno\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.house.GetDataR\x04data\"0\n" +
	"\aGetData\x12%\n" +
	"\x06houses\x18\x01 \x03(\v2\r.house.HousesR\x06houses\"\x96\x02\n" +
	"\x06Houses\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tarea_name\x18\x02 \x01(\tR\bareaName\x12\x14\n" +
	"\x05ctime\x18\x03 \x01(\tR\x05ctime\x12\x19\n" +
	"\bhouse_id\x18\x04 \x01(\x05R\ahouseId\x12\x17\n" +
	"\aimg_url\x18\x05 \x01(\tR\x06imgUrl\x12\x1f\n" +
	"\vorder_count\x18\x06 \x01(\x05R\n" +
	"orderCount\x12\x14\n" +
	"\x05price\x18\a \x01(\x05R\x05price\x12\x1d\n" +
	"\n" +
	"room_count\x18\b \x01(\x05R\troomCount\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12\x1f\n" +
	"\vuser_avatar\x18\n" +
	" \x01(\tR\n" +
	"userAvatar\"V\n" +
	"\x06ImgReq\x12\x18\n" +
	"\ahouseId\x18\x01 \x01(\tR\ahouseId\x12\x18\n" +
	"\aimgData\x18\x02 \x01(\fR\aimgData\x12\x18\n" +
	"\afileExt\x18\x03 \x01(\tR\afileExt\"[\n" +
	"\aImgResp\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\tR\x05errno\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.house.ImgDataR\x04data\"\x1b\n" +
	"\aImgData\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xed\x02\n" +
	"\aRequest\x12\x18\n" +
	"\aacreage\x18\x01 \x01(\tR\aacreage\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x17\n" +
	"\aarea_id\x18\x03 \x01(\tR\x06areaId\x12\x12\n" +
	"\x04beds\x18\x04 \x01(\tR\x04beds\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\tR\bcapacity\x12\x18\n" +
	"\adeposit\x18\x06 \x01(\tR\adeposit\x12\x1a\n" +
	"\bfacility\x18\a \x03(\tR\bfacility\x12\x19\n" +
	"\bmax_days\x18\b \x01(\tR\amaxDays\x12\x19\n" +
	"\bmin_days\x18\t \x01(\tR\aminDays\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\tR\x05price\x12\x1d\n" +
	"\n" +
	"room_count\x18\v \x01(\tR\troomCount\x12\x14\n" +
	"\x05title\x18\f \x01(\tR\x05title\x12\x12\n" +
	"\x04unit\x18\r \x01(\tR\x04unit\x12\x1a\n" +
	"\buserName\x18\x0e \x01(\tR\buserName\"^\n" +
	"\bResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\tR\x05errno\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.house.HouseDataR\x04data\"&\n" +
	"\tHouseData\x12\x19\n" +
	"\bhouse_id\x18\x01 \x01(\tR\ahouseId2\xba\x02\n" +
	"\x05House\x12-\n" +
	"\bPubHouse\x12\x0e.house.Request\x1a\x0f.house.Response\"\x00\x121\n" +
	"\x0eUploadHouseImg\x12\r.house.ImgReq\x1a\x0e.house.ImgResp\"\x00\x12/\n" +
	"\fGetHouseInfo\x12\r.house.GetReq\x1a\x0e.house.GetResp\"\x00\x127\n" +
	"\x0eGetHouseDetail\x12\x10.house.DetailReq\x1a\x11.house.DetailResp\"\x00\x122\n" +
	"\rGetIndexHouse\x12\x0f.house.IndexReq\x1a\x0e.house.GetResp\"\x00\x121\n" +
	"\vSearchHouse\x12\x10.house.SearchReq\x1a\x0e.house.GetResp\"\x00B\x0fZ\r./order;houseb\x06proto3"

var (
	file_proto_house_proto_rawDescOnce sync.Once
	file_proto_house_proto_rawDescData []byte
)

func file_proto_house_proto_rawDescGZIP() []byte {
	file_proto_house_proto_rawDescOnce.Do(func() {
		file_proto_house_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_house_proto_rawDesc), len(file_proto_house_proto_rawDesc)))
	})
	return file_proto_house_proto_rawDescData
}

var file_proto_house_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_house_proto_goTypes = []any{
	(*SearchReq)(nil),   // 0: house.SearchReq
	(*IndexReq)(nil),    // 1: house.IndexReq
	(*DetailReq)(nil),   // 2: house.DetailReq
	(*DetailResp)(nil),  // 3: house.DetailResp
	(*DetailData)(nil),  // 4: house.DetailData
	(*HouseDetail)(nil), // 5: house.HouseDetail
	(*CommentData)(nil), // 6: house.CommentData
	(*GetReq)(nil),      // 7: house.GetReq
	(*GetResp)(nil),     // 8: house.GetResp
	(*GetData)(nil),     // 9: house.GetData
	(*Houses)(nil),      // 10: house.Houses
	(*ImgReq)(nil),      // 11: house.ImgReq
	(*ImgResp)(nil),     // 12: house.ImgResp
	(*ImgData)(nil),     // 13: house.ImgData
	(*Request)(nil),     // 14: house.Request
	(*Response)(nil),    // 15: house.Response
	(*HouseData)(nil),   // 16: house.HouseData
}
var file_proto_house_proto_depIdxs = []int32{
	4,  // 0: house.DetailResp.data:type_name -> house.DetailData
	5,  // 1: house.DetailData.house:type_name -> house.HouseDetail
	6,  // 2: house.HouseDetail.comments:type_name -> house.CommentData
	9,  // 3: house.GetResp.data:type_name -> house.GetData
	10, // 4: house.GetData.houses:type_name -> house.Houses
	13, // 5: house.ImgResp.data:type_name -> house.ImgData
	16, // 6: house.Response.data:type_name -> house.HouseData
	14, // 7: house.House.PubHouse:input_type -> house.Request
	11, // 8: house.House.UploadHouseImg:input_type -> house.ImgReq
	7,  // 9: house.House.GetHouseInfo:input_type -> house.GetReq
	2,  // 10: house.House.GetHouseDetail:input_type -> house.DetailReq
	1,  // 11: house.House.GetIndexHouse:input_type -> house.IndexReq
	0,  // 12: house.House.SearchHouse:input_type -> house.SearchReq
	15, // 13: house.House.PubHouse:output_type -> house.Response
	12, // 14: house.House.UploadHouseImg:output_type -> house.ImgResp
	8,  // 15: house.House.GetHouseInfo:output_type -> house.GetResp
	3,  // 16: house.House.GetHouseDetail:output_type -> house.DetailResp
	8,  // 17: house.House.GetIndexHouse:output_type -> house.GetResp
	8,  // 18: house.House.SearchHouse:output_type -> house.GetResp
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_house_proto_init() }
func file_proto_house_proto_init() {
	if File_proto_house_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_house_proto_rawDesc), len(file_proto_house_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_house_proto_goTypes,
		DependencyIndexes: file_proto_house_proto_depIdxs,
		MessageInfos:      file_proto_house_proto_msgTypes,
	}.Build()
	File_proto_house_proto = out.File
	file_proto_house_proto_goTypes = nil
	file_proto_house_proto_depIdxs = nil
}
