// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.2
// source: order/order.order

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         string                 `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResp) Reset() {
	*x = UpdateResp{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResp) ProtoMessage() {}

func (x *UpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResp.ProtoReflect.Descriptor instead.
func (*UpdateResp) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResp) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *UpdateResp) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         string                 `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data          *GetData               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetResp) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *GetResp) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *GetResp) GetData() *GetData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrdersData          `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetData) Reset() {
	*x = GetData{}
	mi := &file_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetData) ProtoMessage() {}

func (x *GetData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetData.ProtoReflect.Descriptor instead.
func (*GetData) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetData) GetOrders() []*OrdersData {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrdersData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime         string                 `protobuf:"bytes,3,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Days          int32                  `protobuf:"varint,4,opt,name=days,proto3" json:"days,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,6,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	OrderId       int32                  `protobuf:"varint,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersData) Reset() {
	*x = OrdersData{}
	mi := &file_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersData) ProtoMessage() {}

func (x *OrdersData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersData.ProtoReflect.Descriptor instead.
func (*OrdersData) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrdersData) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrdersData) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *OrdersData) GetCtime() string {
	if x != nil {
		return x.Ctime
	}
	return ""
}

func (x *OrdersData) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *OrdersData) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *OrdersData) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *OrdersData) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrdersData) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *OrdersData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrdersData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseId       string                 `protobuf:"bytes,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

func (x *Request) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Request) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Request) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         string                 `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data          *OrderData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *Response) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *Response) GetData() *OrderData {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderData) Reset() {
	*x = OrderData{}
	mi := &file_proto_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderData) ProtoMessage() {}

func (x *OrderData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderData.ProtoReflect.Descriptor instead.
func (*OrderData) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrderData) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.order\x12\x05order\"K\n" +
	"\tUpdateReq\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\":\n" +
	"\n" +
	"UpdateResp\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\tR\x05errno\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg\"8\n" +
	"\x06GetReq\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\"[\n" +
	"\aGetResp\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\tR\x05errno\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg\x12\"\n" +
	"\x04data\x18\x03 \x01(\v2\x0e.order.GetDataR\x04data\"4\n" +
	"\aGetData\x12)\n" +
	"\x06orders\x18\x01 \x03(\v2\x11.order.OrdersDataR\x06orders\"\x84\x02\n" +
	"\n" +
	"OrdersData\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x14\n" +
	"\x05ctime\x18\x03 \x01(\tR\x05ctime\x12\x12\n" +
	"\x04days\x18\x04 \x01(\x05R\x04days\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x17\n" +
	"\aimg_url\x18\x06 \x01(\tR\x06imgUrl\x12\x19\n" +
	"\border_id\x18\a \x01(\x05R\aorderId\x12\x1d\n" +
	"\n" +
	"start_date\x18\b \x01(\tR\tstartDate\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\"z\n" +
	"\aRequest\x12\x19\n" +
	"\bhouse_id\x18\x01 \x01(\tR\ahouseId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12\x1a\n" +
	"\buserName\x18\x04 \x01(\tR\buserName\"^\n" +
	"\bResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\tR\x05errno\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.order.OrderDataR\x04data\"&\n" +
	"\tOrderData\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId2\xa1\x01\n" +
	"\x05Order\x120\n" +
	"\vCreateOrder\x12\x0e.order.Request\x1a\x0f.order.Response\"\x00\x12/\n" +
	"\fGetOrderInfo\x12\r.order.GetReq\x1a\x0e.order.GetResp\"\x00\x125\n" +
	"\fUpdateStatus\x12\x10.order.UpdateReq\x1a\x11.order.UpdateResp\"\x00B\x0fZ\r./order;orderb\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_order_proto_goTypes = []any{
	(*UpdateReq)(nil),  // 0: order.UpdateReq
	(*UpdateResp)(nil), // 1: order.UpdateResp
	(*GetReq)(nil),     // 2: order.GetReq
	(*GetResp)(nil),    // 3: order.GetResp
	(*GetData)(nil),    // 4: order.GetData
	(*OrdersData)(nil), // 5: order.OrdersData
	(*Request)(nil),    // 6: order.Request
	(*Response)(nil),   // 7: order.Response
	(*OrderData)(nil),  // 8: order.OrderData
}
var file_proto_order_proto_depIdxs = []int32{
	4, // 0: order.GetResp.data:type_name -> order.GetData
	5, // 1: order.GetData.orders:type_name -> order.OrdersData
	8, // 2: order.Response.data:type_name -> order.OrderData
	6, // 3: order.Order.CreateOrder:input_type -> order.Request
	2, // 4: order.Order.GetOrderInfo:input_type -> order.GetReq
	0, // 5: order.Order.UpdateStatus:input_type -> order.UpdateReq
	7, // 6: order.Order.CreateOrder:output_type -> order.Response
	3, // 7: order.Order.GetOrderInfo:output_type -> order.GetResp
	1, // 8: order.Order.UpdateStatus:output_type -> order.UpdateResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
