// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getCaptcha.proto

package main

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetCaptcha service

type GetCaptchaService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetCaptcha_StreamService, error)
}

type getCaptchaService struct {
	c    client.Client
	name string
}

func NewGetCaptchaService(name string, c client.Client) GetCaptchaService {
	return &getCaptchaService{
		c:    c,
		name: name,
	}
}

func (c *getCaptchaService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetCaptcha.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getCaptchaService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetCaptcha_StreamService, error) {
	req := c.c.NewRequest(c.name, "GetCaptcha.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getCaptchaServiceStream{stream}, nil
}

type GetCaptcha_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*StreamingResponse, error)
}

type getCaptchaServiceStream struct {
	stream client.Stream
}

func (x *getCaptchaServiceStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getCaptchaServiceStream) Close() error {
	return x.stream.Close()
}

func (x *getCaptchaServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getCaptchaServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getCaptchaServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getCaptchaServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetCaptcha service

type GetCaptchaHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, GetCaptcha_StreamStream) error
}

func RegisterGetCaptchaHandler(s server.Server, hdlr GetCaptchaHandler, opts ...server.HandlerOption) error {
	type getCaptcha interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
	}
	type GetCaptcha struct {
		getCaptcha
	}
	h := &getCaptchaHandler{hdlr}
	return s.Handle(s.NewHandler(&GetCaptcha{h}, opts...))
}

type getCaptchaHandler struct {
	GetCaptchaHandler
}

func (h *getCaptchaHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GetCaptchaHandler.Call(ctx, in, out)
}

func (h *getCaptchaHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetCaptchaHandler.Stream(ctx, m, &getCaptchaStreamStream{stream})
}

type GetCaptcha_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type getCaptchaStreamStream struct {
	stream server.Stream
}

func (x *getCaptchaStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getCaptchaStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getCaptchaStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getCaptchaStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getCaptchaStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}
